# Generated by Django 2.2.28 on 2024-03-25 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='filmak_filma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izenburua', models.CharField(max_length=100)),
                ('zuzendaria', models.CharField(max_length=60)),
                ('urtea', models.IntegerField(max_length=11)),
                ('generoa', models.CharField(max_length=2)),
                ('sipnosia', models.CharField(max_length=500)),
                ('bozkak', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='filmak_bozkatzailea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erabiltzailea_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
