# Generated by Django 2.2.28 on 2024-04-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmaGunea', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmak_bozkatzailea',
            old_name='erabiltzailea_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='filmak_filma',
            name='bozkatzaileak',
            field=models.ManyToManyField(to='FilmaGunea.filmak_bozkatzailea'),
        ),
    ]
