# Generated by Django 2.2.28 on 2024-04-09 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FilmaGunea', '0002_auto_20240409_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmak_bozkatzailea',
            old_name='user',
            new_name='erabiltzailea_id',
        ),
    ]
