# Generated by Django 2.2.28 on 2024-04-10 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FilmaGunea', '0003_auto_20240409_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmak_bozkatzailea',
            old_name='erabiltzailea_id',
            new_name='erabiltzailea',
        ),
    ]
